---

- hosts: all
  become: true
  tasks:


  - name: install apache web server on ubuntu and it modules
    apt:
      name:
         - apache2
         - libapache2-mod-php
         - liapache2-mod-ssl
      state: latest
      update_cache: yes
    when ansible_distribution == "Ubuntu"   
      
 - name: install apache web server on rocky linux and it modules
    dnf:
      name:
         - httpd
         - php
         - mod-ssl
      state: latest
      update_cache: yes
    when ansible_distribution == "Rocky"

