---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates on  Rocky
    tags: always
    dnf:
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: install update on Ubuntu
    tags: always
    apt:
      upgrade: dist
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:


  - name: install apache web server on ubuntu
    tags: apache2, apache, ubuntu
    apt:
      name:
         - apache2
         - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache web server on rocky
    tags: httpd, httpd-24
    dnf:
      name:
         - httpd
         - php
         - mod-ssl
      state: latest
    when: ansible_distribution == "Rocky"
 
 
  - name: copy fo default html file for site
    tags: apache, apache2, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb server on ubuntu ubuntu
    tags: databases, mysql-db, mariadb-database
    package:
      name: 
         - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba server on Rocky
    tags: file-sharing, samba-shared-file
    package:
      name:
         - samba
      state: latest
    when: ansible_distribution == "Rocky"
