---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates on  Rocky
    tags: always
    dnf:
      update_cache: yes
#      changed_when: false #this line unsupported
    when: ansible_distribution == "Rocky"

  - name: install update on Ubuntu
    tags: always
    apt:
      upgrade: dist
 #     changed_when: false # this line unsupported
    when: ansible_distribution == "Ubuntu"


- hosts: all
  become: true
  tasks:

  - name: add ssh key for issa
    tags: always
    authorized_key:
       user: issa
       key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG8cugrAanv/XOcG2gRCQyVTOzbP3ZK/cpRjjRK/c3dj issaszn@server3"




- hosts: workstations
  become: true
  tasks: 
   
  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.12.2/terraform_1.12.2_linux_amd64.zip
      dest: /usr/local/bin/
      remote_src: yes
      owner: root
      group: root
      mode: 0755





- hosts: web_servers
  become: true
  tasks:


  - name: install apache web server on ubuntu
    tags: apache2, apache, ubuntu
    apt:
      name:
         - apache2
         - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache web server on rocky
    tags: httpd, httpd-24
    dnf:
      name:
         - httpd
         - php
      state: latest
    when: ansible_distribution == "Rocky"
  
  - name: start httpd Rocky linux
    tags: apache, rockylinux, httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "Rocky" 
 
  - name: copy fo default html file for site
    tags: apache, apache2, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb server on ubuntu ubuntu
    tags: databases, mysql-db, mariadb-database
    package:
      name: 
         - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba server on Rocky
    tags: file-sharing, samba-shared-file
    package:
      name:
         - samba
      state: latest
    when: ansible_distribution == "Rocky"
